### PR TITLE
uncomment the clojure tests

### PR DESCRIPTION
**Pull request by sjahl**
Noticed that the tests were commented out, looking to close out #532

### CODE REVIEW

**Comment by theferrit32** [comment]
@sjahl I think I found it, I'll just push a commit to this branch

**Comment by theferrit32** [comment]
The error in the latest run might be something @toneillbroad and @tnavatar needs to look at. Maybe related to a missing field in the test data. I can't dedicate more time to looking into it right now. It looks like @toneillbroad put a note in. It is an `error` instead of just a test `fail` because the nil value creates an uncaught nullpointerexception in construct-statement. This happens relatively frequently if a triple is made with a value that is unexpectedly missing from input data, so we may want a more graceful way to handle this.

https://github.com/clingen-data-model/genegraph/blob/073bac09478ac5401bdd0e89c00eec851a2bfc93/test/genegraph/sink/event_test.clj#L12-L22

**Comment by larrybabb** [comment]
@theferrit32 is this your ticket?

**Comment by larrybabb** [comment]
@theferrit32, @tnavatar and/or @toneillbroad can one of you provide some feedback here on what is left to do to close this ticket? 
My recollection is that we should either throw out the clojure tests that are commented out or get them working. I realize this is housekeeping, but I'd be fine with the simple solution of someone moving the commented out tests to a branch (for future reference - if we ever come up for air to work on testing) and remove the cruft that is in the main build branch. 
If one of you can step up and assign this to yourself and close it out that would be super. If I'm missing some bigger picture issue please respond in a comment so we can make progress on this asynchronously.

**Comment by larrybabb** [comment]
@tnavatar can you weigh in on what should be done with the PR?

**Comment by larrybabb** [comment]
@theferrit32 @tnavatar @toneillbroad I'm closing this. It seems obvious that we don't need to address this and if we do we will create another ticket in the future. Please feel free to re-open and leave a comment if you feel otherwise.

**Pull request closed without merging**
