### PR TITLE
Add resolvers, update property names for scv mvp

### PR DESCRIPTION
**Pull request by theferrit32**

### CODE REVIEW

**Review by tnavatar — APPROVED** [review]
Overall looks good--I say proceed though I think it would be good to look at this all-together in the future. One thing (not the most important thing), is that adding too many info level logging messages can get pretty noisy. Would be cautious about dropping too many in (also don't be surprised if I sweep in and demote them to debug level messages in a future PR...)

**Review by toneillbroad — APPROVED** [review]

**Comment by theferrit32** [comment]
Ah yeah I made those info so I could see them without enabling debug everywhere. I'll make them debug on the next PR. It is a substantial amount of output.

**Comment by tnavatar** [comment]
Yeah—I think log output is tunable, but is part of Java init and requires a restart. The Java logging story is overall pretty crummy; I do the same thing you do when I really want to see log output.

**Comment by toneillbroad** [comment]
I may be wrong here, but I am pretty sure that logback can be reconfigured on the fly without restart. I think the scan="true" means to look for config file changes.
<configuration scan="true" scanPeriod="10 seconds">

**Comment by tnavatar** [comment]
You would know better than me. If you can offer advice that would be helpful; like printing debug messages but only from specified namespaces.

**Pull request merged**
